services:
  - type: worker
    name: news-bot
    env: python
    plan: free
    autoDeploy: true
    buildCommand: "pip install -r requirements.txt"
    startCommand: python news_bot_discord_only.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
